name: Bug Report
description: Create a report to help us improve the PreMiD Store
title: Service Name | Service URL
labels: [🐛 Bug]
body:
  - type: markdown
    attributes:
      value: Before submitting a new issue, ensure your bug hasn't already been reported. If it has, reply to the open issue instead.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Provide a clear and concise description of what the bug is
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: Provide clear and unambiguous steps on how to reproduce the bug
      placeholder: |
        1. Go to this link
        2. Click on this
        3. Observe that
  - type: textarea
    validations:
      required: false
    attributes:
      label: "Screenshots"
      description: "Optionally add some screenshots to reinforce your point"
  - type: input
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
  - type: input
    validations:
      required: true
    attributes:
      label: Actual Behavior
      description: Describe what actually happened
  - type: input
    validations:
      required: true
    attributes:
      label: Page URL
      description: The URL you were visiting when the bug happens
  - type: input
    validations:
      required: true
    attributes:
      label: Operating System (OS)
      description: E.g. Windows 11, macOS 12, etc
  - type: input
    validations:
      required: true
    attributes:
      label: Browser
      description: E.g. Chrome, Firefox, etc
  - type: input
    validations:
      required: true
    attributes:
      label: Browser Version
      description: You can get the version by visiting about:support on Firefox or chrome://help on most browsers
